### ISSUE TITLE
How to get  .csv file of testing TSS dataset?

### ISSUE THREAD

**Issue by cl199443** [YunChunChen/WeakMatchNet#1]
test_tss_FG3DCar.csv, test_tss_JODS.csv and  test_tss_PASCAL.csv are not included in the  download_datasets.py . Can you tell me clearly how to get them ? Or directly giving the downloading path.

**Comment by YunChunChen** [comment]
Hi,

Thanks for the question. As I am working on my journal extension of this work, I will be cleaning up the code and provide a step-by-step instruction soon.
